DEPARTEMENTS = {
"01":{"nom":"Ain","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"02":{"nom":"Aisne","region":{"code":32,"nom":"Hauts-de-France"}},
"03":{"nom":"Allier","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"04":{"nom":"Alpes-de-Haute-Provence","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"05":{"nom":"Hautes-Alpes","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"06":{"nom":"Alpes-Maritimes","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"07":{"nom":"Ardèche","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"08":{"nom":"Ardennes","region":{"code":44,"nom":"Grand Est"}},
"09":{"nom":"Ariège","region":{"code":76,"nom":"Occitanie"}},
"10":{"nom":"Aube","region":{"code":44,"nom":"Grand Est"}},
"11":{"nom":"Aude","region":{"code":76,"nom":"Occitanie"}},
"12":{"nom":"Aveyron","region":{"code":76,"nom":"Occitanie"}},
"13":{"nom":"Bouches-du-Rhône","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"14":{"nom":"Calvados","region":{"code":28,"nom":"Normandie"}},
"15":{"nom":"Cantal","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"16":{"nom":"Charente","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"17":{"nom":"Charente-Maritime","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"18":{"nom":"Cher","region":{"code":24,"nom":"Centre-Val de Loire"}},
"19":{"nom":"Corrèze","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"21":{"nom":"Côte-d'Or","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"22":{"nom":"Côtes-d'Armor","region":{"code":53,"nom":"Bretagne"}},
"23":{"nom":"Creuse","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"24":{"nom":"Dordogne","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"25":{"nom":"Doubs","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"26":{"nom":"Drôme","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"27":{"nom":"Eure","region":{"code":28,"nom":"Normandie"}},
"28":{"nom":"Eure-et-Loir","region":{"code":24,"nom":"Centre-Val de Loire"}},
"29":{"nom":"Finistère","region":{"code":53,"nom":"Bretagne"}},
"2A":{"nom":"Corse-du-Sud","region":{"code":94,"nom":"Corse"}},
"2B":{"nom":"Haute-Corse","region":{"code":94,"nom":"Corse"}},
"30":{"nom":"Gard","region":{"code":76,"nom":"Occitanie"}},
"31":{"nom":"Haute-Garonne","region":{"code":76,"nom":"Occitanie"}},
"32":{"nom":"Gers","region":{"code":76,"nom":"Occitanie"}},
"33":{"nom":"Gironde","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"34":{"nom":"Hérault","region":{"code":76,"nom":"Occitanie"}},
"35":{"nom":"Ille-et-Vilaine","region":{"code":53,"nom":"Bretagne"}},
"36":{"nom":"Indre","region":{"code":24,"nom":"Centre-Val de Loire"}},
"37":{"nom":"Indre-et-Loire","region":{"code":24,"nom":"Centre-Val de Loire"}},
"38":{"nom":"Isère","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"39":{"nom":"Jura","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"40":{"nom":"Landes","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"41":{"nom":"Loir-et-Cher","region":{"code":24,"nom":"Centre-Val de Loire"}},
"42":{"nom":"Loire","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"43":{"nom":"Haute-Loire","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"44":{"nom":"Loire-Atlantique","region":{"code":52,"nom":"Pays de la Loire"}},
"45":{"nom":"Loiret","region":{"code":24,"nom":"Centre-Val de Loire"}},
"46":{"nom":"Lot","region":{"code":76,"nom":"Occitanie"}},
"47":{"nom":"Lot-et-Garonne","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"48":{"nom":"Lozère","region":{"code":76,"nom":"Occitanie"}},
"49":{"nom":"Maine-et-Loire","region":{"code":52,"nom":"Pays de la Loire"}},
"50":{"nom":"Manche","region":{"code":28,"nom":"Normandie"}},
"51":{"nom":"Marne","region":{"code":44,"nom":"Grand Est"}},
"52":{"nom":"Haute-Marne","region":{"code":44,"nom":"Grand Est"}},
"53":{"nom":"Mayenne","region":{"code":52,"nom":"Pays de la Loire"}},
"54":{"nom":"Meurthe-et-Moselle","region":{"code":44,"nom":"Grand Est"}},
"55":{"nom":"Meuse","region":{"code":44,"nom":"Grand Est"}},
"56":{"nom":"Morbihan","region":{"code":53,"nom":"Bretagne"}},
"57":{"nom":"Moselle","region":{"code":44,"nom":"Grand Est"}},
"58":{"nom":"Nièvre","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"59":{"nom":"Nord","region":{"code":32,"nom":"Hauts-de-France"}},
"60":{"nom":"Oise","region":{"code":32,"nom":"Hauts-de-France"}},
"61":{"nom":"Orne","region":{"code":28,"nom":"Normandie"}},
"62":{"nom":"Pas-de-Calais","region":{"code":32,"nom":"Hauts-de-France"}},
"63":{"nom":"Puy-de-Dôme","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"64":{"nom":"Pyrénées-Atlantiques","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"65":{"nom":"Hautes-Pyrénées","region":{"code":76,"nom":"Occitanie"}},
"66":{"nom":"Pyrénées-Orientales","region":{"code":76,"nom":"Occitanie"}},
"67":{"nom":"Bas-Rhin","region":{"code":44,"nom":"Grand Est"}},
"68":{"nom":"Haut-Rhin","region":{"code":44,"nom":"Grand Est"}},
"69":{"nom":"Rhône","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"70":{"nom":"Haute-Saône","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"71":{"nom":"Saône-et-Loire","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"72":{"nom":"Sarthe","region":{"code":52,"nom":"Pays de la Loire"}},
"73":{"nom":"Savoie","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"74":{"nom":"Haute-Savoie","region":{"code":84,"nom":"Auvergne-Rhône-Alpes"}},
"75":{"nom":"Paris","region":{"code":11,"nom":"Île-de-France"}},
"76":{"nom":"Seine-Maritime","region":{"code":28,"nom":"Normandie"}},
"77":{"nom":"Seine-et-Marne","region":{"code":11,"nom":"Île-de-France"}},
"78":{"nom":"Yvelines","region":{"code":11,"nom":"Île-de-France"}},
"79":{"nom":"Deux-Sèvres","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"80":{"nom":"Somme","region":{"code":32,"nom":"Hauts-de-France"}},
"81":{"nom":"Tarn","region":{"code":76,"nom":"Occitanie"}},
"82":{"nom":"Tarn-et-Garonne","region":{"code":76,"nom":"Occitanie"}},
"83":{"nom":"Var","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"84":{"nom":"Vaucluse","region":{"code":93,"nom":"Provence-Alpes-Côte d'Azur"}},
"85":{"nom":"Vendée","region":{"code":52,"nom":"Pays de la Loire"}},
"86":{"nom":"Vienne","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"87":{"nom":"Haute-Vienne","region":{"code":75,"nom":"Nouvelle-Aquitaine"}},
"88":{"nom":"Vosges","region":{"code":44,"nom":"Grand Est"}},
"89":{"nom":"Yonne","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"90":{"nom":"Territoire de Belfort","region":{"code":27,"nom":"Bourgogne-Franche-Comté"}},
"91":{"nom":"Essonne","region":{"code":11,"nom":"Île-de-France"}},
"92":{"nom":"Hauts-de-Seine","region":{"code":11,"nom":"Île-de-France"}},
"93":{"nom":"Seine-Saint-Denis","region":{"code":11,"nom":"Île-de-France"}},
"94":{"nom":"Val-de-Marne","region":{"code":11,"nom":"Île-de-France"}},
"95":{"nom":"Val-d'Oise","region":{"code":11,"nom":"Île-de-France"}},
"971":{"nom":"Guadeloupe","region":{"code":1,"nom":"Guadeloupe"}},
"972":{"nom":"Martinique","region":{"code":2,"nom":"Martinique"}},
"973":{"nom":"Guyane","region":{"code":3,"nom":"Guyane"}},
"974":{"nom":"La Réunion","region":{"code":4,"nom":"La Réunion"}},
"976":{"nom":"Mayotte","region":{"code":6,"nom":"Mayotte"}}
}